tmux:
    symbols:
        branch: "⎇ "
        hashprefix: "#"
        ahead: " ↑"
        behind: " ↓"
        staged: " ●"
        conflict: " ✖"
        modified: " ✚"
        untracked: " ?"
        stashed: " ⚑"
        insertions: Σ
        deletions: Δ
        clean: " ✔ pulito"

    styles:
        clear: "#[none]"
        state: "#[fg=red,bold]"
        branch: "#[fg=cyan,bold]"
        remote: "#[fg=yellow]"
        divergence: "#[fg=yellow,bold]"
        staged: "#[fg=green,bold]"
        conflict: "#[fg=red,bold]"
        modified: "#[fg=blue,bold]"
        untracked: "#[fg=magenta,bold]"
        stashed: "#[fg=cyan]"
        insertions: "#[fg=green]"
        deletions: "#[fg=red]"
        clean: "#[fg=green]"

    layout: [branch, divergence, " ", flags]

    options:
        branch_max_len: 28
        branch_trim: right
        ellipsis: …
        hide_clean: false
