tmux:
    symbols:
        branch: "⎇ "
        hashprefix: "#"
        ahead: " ↑"
        behind: " ↓"
        staged: " ●"
        conflict: " ✖"
        modified: " ✚"
        untracked: " ?"
        stashed: " ⚑"
        insertions: Σ
        deletions: Δ
        clean: " ✔ pulito"

    styles:
        clear: "#[none]"
        state: "#[fg=#f7768e,bold]"
        branch: "#[fg=#7dcfff,bold]"
        remote: "#[fg=#e0af68]"
        divergence: "#[fg=#e0af68,bold]"
        staged: "#[fg=#9ece6a,bold]"
        conflict: "#[fg=#f7768e,bold]"
        modified: "#[fg=#7aa2f7,bold]"
        untracked: "#[fg=#bb9af7,bold]"
        stashed: "#[fg=#7dcfff]"
        insertions: "#[fg=#9ece6a]"
        deletions: "#[fg=#f7768e]"
        clean: "#[fg=#9ece6a]"

    layout: [branch, divergence, " ", flags]

    options:
        branch_max_len: 28
        branch_trim: right
        ellipsis: …
        hide_clean: false
